"""Video assembly — stitch PNG renders into MP4 via ffmpeg.

Takes a recipe's render directory (sorted PNGs), assembles into
an MP4 timelapse at configurable fps. Supports overlay compositing
via ffmpeg drawtext filters.

Audio is generated by oceancanvas.audio (RFC-010 four-layer synthesis) when
the caller passes recipe values + audio params. The synthesised WAV is mixed
into the MP4's AAC track by ffmpeg.

Tension arc (RFC-011) drives ffmpeg ``eq=saturation`` + ``vignette=angle`` via
``sendcmd`` keyframes sampled at 1Hz: as tension rises, saturation eases off
and the vignette tightens. Audio dynamics follow the same arc array
(``oceancanvas.audio``) so visual + audio coupling is in lockstep.
"""

from __future__ import annotations

import math
import subprocess
from pathlib import Path

from oceancanvas.audio import AudioParams, build_audio_track
from oceancanvas.log import get_logger


def assemble_video(
    recipe_name: str,
    renders_dir: Path,
    output_path: Path,
    fps: int = 12,
    dates: list[str] | None = None,
    overlay_date: bool = True,
    overlay_attribution: bool = True,
    audio_params: AudioParams | None = None,
    audio_values: list[float] | None = None,
    audio_dates: list[str] | None = None,
    audio_moments: list[dict] | None = None,
    tension_arc: list[float] | None = None,
    hold_at_frame: int | None = None,
    hold_duration_sec: float = 0.0,
    channel_mix: dict[str, dict] | None = None,
    audio_eq: dict[str, float] | None = None,
) -> Path:
    """Assemble PNG renders into an MP4 video via ffmpeg.

    Args:
        recipe_name: Recipe slug (renders are in renders_dir/recipe_name/).
        renders_dir: Root renders directory.
        output_path: Where to write the MP4.
        fps: Frames per second.
        dates: Specific dates to include (default: all, sorted).
        overlay_date: Burn date stamp into each frame.
        overlay_attribution: Burn attribution footer.

    Returns:
        Path to the output MP4.
    """
    logger = get_logger()
    recipe_dir = renders_dir / recipe_name

    if not recipe_dir.exists():
        msg = f"No renders directory: {recipe_dir}"
        raise FileNotFoundError(msg)

    # Collect PNG files
    if dates:
        png_files = [recipe_dir / f"{d}.png" for d in dates]
        png_files = [p for p in png_files if p.exists()]
    else:
        png_files = sorted(recipe_dir.glob("*.png"))
        # Exclude "latest.png" from timeline
        png_files = [p for p in png_files if p.stem != "latest"]

    if not png_files:
        msg = f"No PNG files found in {recipe_dir}"
        raise FileNotFoundError(msg)

    logger.info(
        "Assembling %d frames into %s at %d fps",
        len(png_files), output_path, fps,
    )

    # Create a concat file listing all PNGs with duration. If a Record Moment
    # hold is requested (RFC-011 / PRD-006), the held frame is given a longer
    # duration so the video lingers; build_audio_track gets the same hold so
    # audio stays in sync.
    concat_path = output_path.with_suffix(".concat.txt")
    frame_duration = f"{1/fps:.6f}"
    valid_hold = (
        hold_at_frame is not None
        and 0 <= hold_at_frame < len(png_files)
        and hold_duration_sec > 0
    )
    with concat_path.open("w") as f:
        for i, png in enumerate(png_files):
            f.write(f"file '{png.resolve()}'\n")
            if valid_hold and i == hold_at_frame:
                # Held frame gets the normal frame duration plus the extra hold
                held = (1 / fps) + hold_duration_sec
                f.write(f"duration {held:.6f}\n")
            else:
                f.write(f"duration {frame_duration}\n")
        # Repeat last frame to avoid ffmpeg cutting it short
        f.write(f"file '{png_files[-1].resolve()}'\n")

    # Build generative audio track when the caller supplies values + params
    audio_path = None
    if audio_params and audio_values:
        try:
            audio_path = output_path.with_suffix(".audio.wav")
            build_audio_track(
                audio_path,
                values=audio_values,
                dates=audio_dates or [],
                moments=audio_moments or [],
                params=audio_params,
                fps=fps,
                arc=tension_arc,
                hold_at_frame=hold_at_frame if valid_hold else None,
                hold_duration_sec=hold_duration_sec if valid_hold else 0.0,
                channel_mix=channel_mix,
            )
        except Exception as e:  # noqa: BLE001
            logger.warning("Audio synthesis failed (%s) — exporting silent", e)
            audio_path = None

    # Build ffmpeg command
    duration_sec = len(png_files) / fps
    arc_chain = _build_arc_chain(tension_arc, duration_sec) if tension_arc else ""
    vf = _build_filters(overlay_date, overlay_attribution, png_files, arc_chain)
    cmd = [
        "ffmpeg", "-y",
        "-f", "concat",
        "-safe", "0",
        "-i", str(concat_path),
    ]
    if audio_path:
        cmd.extend(["-i", str(audio_path)])
    # Only add filter if we have drawtext support
    if vf != "null":
        cmd.extend(["-vf", vf])
    cmd.extend([
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-preset", "medium",
        "-crf", "23",
    ])
    if audio_path:
        # 3-band peaking EQ matching the browser sidebar — bass / mid / treble
        # gains in dB. Only emit filters that actually move the needle to keep
        # ffmpeg's filter graph short.
        af_chain = []
        if audio_eq:
            bass = float(audio_eq.get("bass", 0))
            mid = float(audio_eq.get("mid", 0))
            treble = float(audio_eq.get("treble", 0))
            if abs(bass) >= 0.1:
                af_chain.append(f"equalizer=f=80:t=h:width=80:g={bass:.2f}")
            if abs(mid) >= 0.1:
                af_chain.append(f"equalizer=f=1000:t=h:width=2000:g={mid:.2f}")
            if abs(treble) >= 0.1:
                af_chain.append(f"equalizer=f=8000:t=h:width=4000:g={treble:.2f}")
        if af_chain:
            cmd.extend(["-af", ",".join(af_chain)])
        cmd.extend(["-c:a", "aac", "-b:a", "192k", "-shortest"])
    cmd.extend([
        "-movflags", "+faststart",
        str(output_path),
    ])

    logger.info("Running ffmpeg: %s", " ".join(cmd[:6]) + " ...")

    result = subprocess.run(
        cmd,
        capture_output=True,
        timeout=600,
        check=False,
    )

    # Clean up temp files
    concat_path.unlink(missing_ok=True)
    if audio_path:
        audio_path.unlink(missing_ok=True)

    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace")
        msg = f"ffmpeg failed (exit {result.returncode}): {stderr[-500:]}"
        raise RuntimeError(msg)

    size = output_path.stat().st_size
    duration = len(png_files) / fps
    logger.info(
        "Video assembled: %s (%.1f MB, %.1fs at %d fps)",
        output_path, size / 1024 / 1024, duration, fps,
    )
    return output_path


def _build_filters(
    overlay_date: bool,
    overlay_attribution: bool,
    png_files: list[Path],  # noqa: ARG001 — kept for backwards-compat with callers
    arc_chain: str = "",
) -> str:
    """Build ffmpeg filter string for overlays + arc-keyed colour grade.

    ``arc_chain`` is an optional ffmpeg filter sub-chain produced by
    ``_build_arc_chain`` that keys eq=saturation + vignette=angle from the
    tension arc via sendcmd. When supplied it is composed *before* the
    overlay filters so the grade is applied first and overlays read on top
    of the graded image.
    """
    filters = []

    if arc_chain:
        filters.append(arc_chain)

    if overlay_date:
        # Extract dates from filenames for per-frame date stamp
        # Use ffmpeg's frame number to index into the date list
        # Simple approach: burn the recipe name (date is in the filename)
        filters.append(
            "drawtext=text='%{pts\\:gmtime\\:0\\:%Y}':"
            "fontsize=24:fontcolor=white@0.6:"
            "x=w-tw-20:y=20:font=monospace"
        )

    if overlay_attribution:
        filters.append(
            "drawtext=text='OceanCanvas':"
            "fontsize=16:fontcolor=white@0.4:"
            "x=20:y=h-30:font=monospace"
        )

    if not filters:
        return "null"
    return ",".join(filters)


def _build_arc_chain(arc: list[float], duration_sec: float) -> str:
    """Emit ``sendcmd=...,eq=saturation=1.0,vignette=angle=PI/5`` chain that
    keys eq saturation and vignette aperture from the per-frame arc.

    Sampled at 1Hz: each keypoint is a ``T eq saturation V, vignette angle A;``
    entry. Filter graph length is bounded by duration in seconds (≤60 keys
    for a 60s timelapse).

    Mappings (RFC-011 §"ffmpeg filter graph consumption"):
      • saturation = 1.0 - 0.35 * arc[t]   — image cools toward the peak
      • vignette angle = PI/5 - PI/15 * arc[t] — vignette tightens at peak
    """
    if not arc or duration_sec <= 0:
        return ""

    # 1Hz keypoints: at t = 0, 1, 2, ..., ceil(duration_sec)
    n_keys = int(duration_sec) + 1
    cmds: list[str] = []
    for k in range(n_keys):
        t = float(k)
        # Index into arc array via fractional time
        frac = t / duration_sec if duration_sec > 0 else 0.0
        idx = max(0, min(len(arc) - 1, int(round(frac * (len(arc) - 1)))))
        v = max(0.0, min(1.0, arc[idx]))
        saturation = 1.0 - 0.35 * v
        angle = math.pi / 5 - (math.pi / 15) * v
        cmds.append(f"{t:.2f} eq saturation {saturation:.4f}, vignette angle {angle:.5f};")

    cmd_str = " ".join(cmds)
    # sendcmd injects parameter changes into eq + vignette at the scheduled times.
    return f"sendcmd=c='{cmd_str}',eq=saturation=1.0,vignette=angle=PI/5"


def get_video_info(recipe_name: str, renders_dir: Path) -> dict:
    """Get info about available frames for a recipe."""
    recipe_dir = renders_dir / recipe_name
    if not recipe_dir.exists():
        return {"frames": 0, "dates": []}

    pngs = sorted(recipe_dir.glob("*.png"))
    pngs = [p for p in pngs if p.stem != "latest"]
    dates = [p.stem for p in pngs]

    return {
        "recipe": recipe_name,
        "frames": len(dates),
        "dates": dates,
        "first": dates[0] if dates else None,
        "last": dates[-1] if dates else None,
    }
